"""Load adapter configuration from the upstream config.yaml schema."""

from __future__ import annotations

import os
from pathlib import Path

import yaml


def load_adapter_config(path: Path) -> dict:
    """Read ``config.yaml`` and return the kwargs an adapter constructor expects.

    Schema (v0.2.1)::

        robot:
          ip: "192.168.50.31"
          ssh_user: "ubuntu"
          ssh_pass: "turtlebot4"
          namespace: "turtlebot468"
        workspace:
          dir: "~/my_workspace"
        build:                              # optional, defaults to campus_guide
          packages: ["campus_nav_llm"]
        launch:                             # optional, defaults to campus_guide
          package: "campus_nav_llm"
          file: "navigation_mode.launch.py"
        health:                             # optional, defaults to campus_guide
          user_input_topic: "/user_input"
        dds:                                # optional
          discovery_port: 11811
    """
    if not path.exists():
        raise FileNotFoundError(path)
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    robot = data.get("robot") or {}
    workspace = data.get("workspace") or {}
    build = data.get("build") or {}
    launch = data.get("launch") or {}
    health = data.get("health") or {}
    dds = data.get("dds") or {}

    required = ("ip", "ssh_user", "ssh_pass", "namespace")
    missing = [k for k in required if not robot.get(k)]
    if missing:
        raise ValueError(f"config.yaml missing required robot field(s): {', '.join(missing)}")

    workspace_dir_raw = workspace.get("dir")
    workspace_dir = os.path.expanduser(workspace_dir_raw) if workspace_dir_raw else None

    return {
        "ip": robot["ip"],
        "ssh_user": robot["ssh_user"],
        "ssh_pass": robot["ssh_pass"],
        "namespace": robot["namespace"],
        "workspace_dir": workspace_dir,
        "build_packages": build.get("packages", ["campus_nav_llm"]),
        "launch_package": launch.get("package", "campus_nav_llm"),
        "launch_file": launch.get("file", "navigation_mode.launch.py"),
        "user_input_topic": health.get("user_input_topic", "/user_input"),
        "discovery_port": int(dds.get("discovery_port", 11811)),
    }


def load_known_poses(path: Path) -> dict[str, dict]:
    """Return the optional ``known_poses`` map from config.yaml (or {})."""
    if not path.exists():
        raise FileNotFoundError(path)
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return data.get("known_poses") or {}


def _yaml_dq(value: str) -> str:
    """Escape a string for a YAML double-quoted scalar."""
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\r", "\\r").replace("\n", "\\n")


def render_config_template(
    *,
    ip: str | None = None,
    ssh_user: str | None = None,
    ssh_pass: str | None = None,
    namespace: str | None = None,
    discovery_port: int = 11811,
) -> str:
    """Render a starter config.yaml as text (used by `robobench init`).

    The active ``robot`` and ``dds`` sections are filled from the given values
    (placeholders when omitted); optional sections are emitted commented-out as
    inline documentation. The result parses cleanly via ``load_adapter_config``.
    """
    ip = _yaml_dq(ip or "192.168.x.x")
    ssh_user = _yaml_dq(ssh_user or "ubuntu")
    ssh_pass = _yaml_dq(ssh_pass or "turtlebot4")
    namespace = _yaml_dq(namespace or "turtlebot468")
    return f"""\
# robobench config — generated by `robobench init`.
# Required: the robot block. Everything else is optional (defaults shown).

robot:
  ip: "{ip}"          # robot's IP on your LAN
  ssh_user: "{ssh_user}"
  ssh_pass: "{ssh_pass}"
  namespace: "{namespace}"  # robot's ROS namespace

dds:
  discovery_port: {discovery_port}      # FastDDS Discovery Server port

# --- optional sections (uncomment + edit as needed) ---

# workspace:
#   dir: "~/my_ros2_ws"          # required for `robobench bringup` (colcon build)

# build:
#   packages: ["my_nav_pkg"]     # default: ["campus_nav_llm"]

# launch:
#   package: "my_nav_pkg"        # default: "campus_nav_llm"
#   file: "bringup.launch.py"    # default: "navigation_mode.launch.py"

# health:
#   user_input_topic: "/my_cmd"  # default: "/user_input"

# known_poses:                   # named poses for `robobench bringup --pose NAME`
#   home: {{ x: 0.0, y: 0.0, theta: 0.0 }}
"""


def resolve_pose(value: str, known_poses: dict[str, dict]) -> tuple[float, float, float]:
    """Resolve a pose name or a raw 'x y theta' string to (x, y, theta)."""
    if value in known_poses:
        p = known_poses[value]
        try:
            return (float(p["x"]), float(p["y"]), float(p["theta"]))
        except (KeyError, TypeError, ValueError) as exc:
            raise ValueError(
                f"known pose '{value}' is malformed; expected numeric x, y, theta"
            ) from exc
    _POSE_PARTS = 3
    parts = value.split()
    if len(parts) == _POSE_PARTS:
        try:
            x, y, theta = (float(p) for p in parts)
            return (x, y, theta)
        except ValueError:
            pass
    known = ", ".join(sorted(known_poses)) or "(none configured)"
    raise ValueError(f"unknown pose '{value}'; known: {known}; or pass 'x y theta'")
